// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || "https://placeholder.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      "placeholder-anon-key";

    const request = getRequest();
    const authHeader = request?.headers?.get("authorization");
    const token = authHeader?.startsWith("Bearer ") ? authHeader.replace("Bearer ", "") : null;

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    if (token && SUPABASE_URL !== "https://placeholder.supabase.co") {
      try {
        const { data, error } = await supabase.auth.getClaims(token);
        if (!error && data?.claims?.sub) {
          return next({
            context: {
              supabase,
              userId: data.claims.sub,
              claims: data.claims,
            },
          });
        }
      } catch (err) {
        console.warn("[Supabase Auth] Fallback to anonymous context:", err);
      }
    }

    // Fallback user context
    const defaultUserId = "00000000-0000-0000-0000-000000000001";
    return next({
      context: {
        supabase,
        userId: defaultUserId,
        claims: { sub: defaultUserId },
      },
    });
  },
);
